version: '3.9'

services:
  backend:
    container_name: stax_backend
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
    expose:
      - "8000"

  backend_nginx:
    container_name: stax_backend_nginx
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./backend/staticfiles:/static
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
    restart: always

  frontend:
    container_name: stax_frontend
    build: ./frontend
    ports:
      - "80:80"
    restart: always
