version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stax_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=some-strong-secret-key
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: stax_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000/api/
    depends_on:
      - backend
    restart: always
